# Generated by Django 5.2.9 on 2025-12-25 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='首页内容(支持html)')),
                ('height', models.IntegerField(default=800, null=True, verbose_name='高度(px)')),
            ],
            options={
                'verbose_name': '首页定制',
                'verbose_name_plural': '首页定制',
                'db_table': 'bbs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BulletinBoard_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '公告API',
                'verbose_name_plural': '公告API',
                'db_table': 'BulletinBoard',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DownloadUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile', models.CharField(default='NEWPROGRAM', max_length=50, verbose_name='名称')),
                ('urls', models.CharField(max_length=200000, verbose_name='链接')),
                ('image', models.CharField(max_length=200000, verbose_name='演示图片链接')),
                ('text', models.TextField(blank=True, null=True, verbose_name='说明(支持html)')),
                ('height', models.IntegerField(default=400, null=True, verbose_name='高度(px)')),
            ],
            options={
                'verbose_name': '下载链接',
                'verbose_name_plural': '下载链接',
                'db_table': 'downloadurls',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.CharField(blank=True, max_length=50, verbose_name='账号')),
                ('uuid', models.CharField(max_length=16, verbose_name='用户唯一标识')),
                ('operation_type', models.CharField(max_length=50, verbose_name='操作类型')),
                ('operation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='操作描述')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'OperationLog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='operationtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='说明')),
                ('coins', models.IntegerField(default=0, verbose_name='点数')),
            ],
            options={
                'verbose_name': '操作接口',
                'verbose_name_plural': '操作接口',
                'db_table': 'operationtype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='registrationcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codes', models.CharField(max_length=20, verbose_name='注册码')),
                ('user', models.CharField(blank=True, max_length=50, verbose_name='使用账号')),
                ('Status', models.IntegerField(default=0, verbose_name='使用状态')),
                ('time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='使用时间')),
            ],
            options={
                'verbose_name': '注册码',
                'verbose_name_plural': '注册码',
                'db_table': 'RegistrationCode',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/uploads/admin/%Y%m%d/', verbose_name='文件')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('Account', models.CharField(blank=True, max_length=50, verbose_name='上传用户')),
                ('FileType', models.CharField(blank=True, max_length=20, verbose_name='文件类型')),
            ],
            options={
                'verbose_name': '上传文件',
                'verbose_name_plural': '上传文件',
                'db_table': 'UploadFile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.CharField(max_length=12, unique=True, verbose_name='账号')),
                ('nick_name', models.CharField(default='AT用户93148106', max_length=20, verbose_name='昵称')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('avatar', models.CharField(default='default/default.png', max_length=200, verbose_name='头像')),
                ('coins', models.IntegerField(default=0, verbose_name='金币')),
                ('bands', models.IntegerField(default=0, verbose_name='封禁状态')),
                ('vip', models.IntegerField(default=0, verbose_name='vip')),
                ('signature', models.CharField(default='这是新的一天', max_length=60, verbose_name='签名')),
                ('UniqueIdentification', models.CharField(blank=True, max_length=16, verbose_name='唯一标识')),
                ('devloper', models.IntegerField(default=0, verbose_name='开发者状态')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后登录时间')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
